### ISSUE TITLE
Ensure user owns .cache directory

### ISSUE THREAD

**Issue by eby** [aadl/catalog-stations#21]
Things don't launch right now if `.cache` directory is owned by root for chrome. Also should fix the other two files that are created with become.

Fixed on current ones with this playbook:

```yaml
---
- hosts: all
  become: true
  tasks:
  - name: Fix .cache directory
    ansible.builtin.file:
      path: "/home/{{ ansible_ssh_user }}/.config"
      state: directory
      recurse: yes
      owner: "{{ ansible_ssh_user }}"
      group: "{{ ansible_ssh_user }}"
  - name: Fix .idesktop directory
    ansible.builtin.file:
      path: "/home/{{ ansible_ssh_user }}/.idesktop"
      state: directory
      recurse: yes
      owner: "{{ ansible_ssh_user }}"
      group: "{{ ansible_ssh_user }}"
  - name: Fix .ideskrc
    ansible.builtin.file:
      path: "/home/{{ ansible_ssh_user }}/.ideskrc"
      owner: "{{ ansible_ssh_user }}"
      group: "{{ ansible_ssh_user }}"
```
